### ISSUE TITLE
IPv6 compatiblity

### ISSUE THREAD

**Issue by Somebodyisnobody** [ckanibal/crema#1]
Crema returns a HTTP 500 error on https://crema.clonkspot.org, when a game with the upcoming IPv6 support of LegacyClonk is being hosted.

See also: [Branch ipv6](https://github.com/legacyclonk/LegacyClonk/tree/ipv6)

**Comment by ckanibal** [comment]
Fixed in 8d093fcb3a135710da6ddaab51907d4719e81362.
